language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda create --yes -n test
    - conda activate test
    - conda install -y --file https://raw.githubusercontent.com/ryanlayer/samplot/master/requirements.txt
      
install:
    - git clone https://github.com/ryanlayer/samplot.git


script:
    - cd samplot/test/func
    - bash samplot_test.sh
    - cd ../unit/
    - python samplot_test.py
